{{- if .Values.ingress.enabled -}}
{{- $fullName := include "catanie.fullname" . -}}
{{- $serviceName := include "catanie.fullname" . -}}
{{- $servicePort := .Values.service.externalPort -}}
{{- $host := .Values.ingress.host -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "catanie.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
  - secretName: catanieservice
    hosts:
    - {{ $host }}
  rules:
    - host: {{ $host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
{{- end -}}
