apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "name" . }}
data:
  {{- range $path, $d := .Files.Glob "config/*.*" }}
  {{ base $path }}: |-
  {{- $d | toString | nindent 4 }}
  {{- end }}
