kind: PersistentVolume
apiVersion: v1
metadata:
  name: pvjhub-db
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  mountOptions:
    - hard
    - sync
    - vers=4.2
  nfs:
    path: /nfs/jhub-db
    server: 10.244.0.1
