apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "catamel.fullname" . }}
  labels:
{{ include "catamel.labels" . | indent 4 }}
data:
  {{- range $path, $d := .Files.Glob "config/*.*" }}
  {{ base $path }}: |-
  {{- $d | toString | nindent 4 }}
  {{- end }}
