apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "catamel.fullname" . }}
  labels:
{{ include "catamel.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "catamel.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "catamel.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "/bin/sh","-c","pwd; ls -al . ; ls -al server; cat server/config.json; echo 'Environment:' {{ .Release.Namespace }}; node ." ]
          env:
          - name: NODE_ENV
            value: {{ .Release.Namespace }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.internalPort }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.internalPort }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
            {{- range $path, $d := .Files.Glob "config/*.*" }}
            - name: config-volume
              mountPath: /home/node/app/server/{{ base $path }}
              subPath: {{ base $path }}
            {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "catamel.fullname" . }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
